# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 817d668625672c10b83320d42560c591f74ad2819a118e4d7ba3dd340f96ec7fce1c7b2dc7e47a9d66330df8b3a593bb627d4a5c231e0ed52079f8ceeafce856

test:
  secret_key_base: 839137f2f82e3331ce7345ecd1a62b19d4f66c2b5773d3543e3e9274720ec24ac09ee9cb3d523135bd8c261c5af167366c34a24e5fb632a3d51f1ac027a9c6f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
